---
  - hosts: all
    become: yes
    roles:
     - common

  - hosts: slotmachine
    become: yes
    roles:
     - node
     - docker

  - hosts: slotmachine_db
    become: yes
    roles:
      - mongodb