---
- name: Download jenkins repo
  command: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Download
  get_url:
    url: https://pkg.jenkins.io/debian-stable binary/
    dest: /etc/apt/sources.list

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install the package Jenkins
  apt:
    name: jenkins
    state: present