---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Download
  get_url:
    url: https://pkg.jenkins.io/debian-stable binary/
    dest: /etc/apt/sources.list

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install the package Jenkins
  apt:
    name: jenkins
    state: present